rapidsai/cusignal

README.md

Addition of GTC DC slides and modification of GPU reqs

---

README.md

I know there had been some confusion about exactly which commands I used to test cuSignal on Windows, so I went back with a fresh conda environment and stepped through the commands again to double check. These updated instructions should get anyone with working Windows installs of Anaconda3 and the Nvidia CUDA Toolkit passing the included tests.
Also, this is my first PR, so let me know if I'm doing anything incorrectly. Thanks!

[REVIEW] Update Win install instructions

---

notebooks/sdr_wfm_demod.ipynb

Added WFM demodulation notebook using SoapySDR.

Added Simple WFM Demodulation

---

CHANGELOG.md
README.md
conda/environments/cusignal_base.yml
conda/environments/cusignal_full.yml

Updated environment and readme

[REVIEW] updated to cuda 10.2

---

ci/release/update-version.sh

Removes unnecessary copy-pastes

[REVIEW] Fix update-version.sh [skip-ci]

---

CHANGELOG.md
README.md

Fix typos in README

---

CHANGELOG.md
python/cusignal/acoustics.py

Add Apache 2.0 header to file.

[REVIEW] Adding license header to acoustics.py

---

CHANGELOG.md

[REVIEW] Branch 0.14 merge 0.13

---

CHANGELOG.md

Auto-merge triggered by push to `branch-0.13` that creates a PR to keep `branch-0.14` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.13 to branch-0.14 [skip ci]

---

CHANGELOG.md
python/cusignal/signaltools.py

This reduces computation time by not recreating the window it every call.

[REVIEW] Updated decimate function to use an existing FIR window

---

CHANGELOG.md
python/cusignal/_upfirdn.py
python/cusignal/benchmark/bench_signaltools.py
python/cusignal/test/test_signaltools.py

The PR integrate a CuPy raw kernel for upfirdn with 2d input arrays. Previously, only 1d input arrays had a CuPy raw kernel.
It also cleans up the Numba 2d version and add int type casting optimization, that had be previously add to the Numba 1d kernel.
To make `cusignal.upfirdn` act more like `scipy.signal.upfirdn`, precompile for `GPUKernel.UPFIRDN2D` has been removed and both kernels are compile with `GPUKernel.UPFIRDN`. Then at runtime the appropriate kernel is chosen based on input dimension.
Tests and benchmarks have been added.
As excepted, CuPy kernel are roughly 2x faster. For very small scenarios, `scipy.signal.upfirdn` performs faster.
```bash
----------------------------------------------------------------------------------------------- benchmark 'UpFirDn': 54 tests …
```

[REVIEW] Add CuPy raw kernel for upfirdn 2d

---

CHANGELOG.md
README.md

This PR:
* Fixes spelling errors
* Corrects conda install instructions for cuSignal and doesn't force a version on the nightlies
* Adds blogs and articles featuring cuSignal for quick reference

[skip-ci] README Update - Add Blogs, Fix Conda Install Docs, and Fix Spelling Mistakes

---

CHANGELOG.md
python/cusignal/__init__.py
python/cusignal/filtering/__init__.py
python/cusignal/filtering/filtering.py

This pull-request implements a GPU accelerated `lfilter` function originally ported from PyTorch. This code aims to address issue #7.
closes #7

[WIP] Implement lfilter method.

---

CHANGELOG.md
python/cusignal/filtering/filtering.py

Add notes section that clarifies cusignal's linear filter implementation and its performance w.r.t. scipy.signal.

[REVIEW] Add clarifying documentation for lfilter perf

---

CHANGELOG.md
README.md

Ease of use improvements for the cuSignal README, including:
* Addition of table of contents
* Instructions on how to run pytest-benchmark
* Instructions on how to precompile kernels
* Add API doc links for stable and nightly releases
closes https://github.com/rapidsai/cusignal/issues/86

[skip-ci] [REVIEW] Update cuSignal README

---

CHANGELOG.md
python/cusignal/conftest.py
python/cusignal/convolution/_convolution_cuda.py

Addressing flake8 errors brought up in https://github.com/rapidsai/cusignal/pull/103

[REVIEW] Fix flake8 errors

---

CHANGELOG.md
README.md

Spelling fix and updating cuSignal versions in README from 0.13 to 0.14.

[REVIEW] Update readme for 0.14

---

CHANGELOG.md
python/cusignal/convolution/_convolution_cuda.py
python/cusignal/convolution/convolve.py
python/cusignal/convolution/correlate.py
python/cusignal/filtering/_sosfilt_cuda.py
python/cusignal/filtering/_upfirdn_cuda.py
python/cusignal/filtering/filtering.py
python/cusignal/filtering/resample.py
python/cusignal/spectral_analysis/_spectral_cuda.py
python/cusignal/spectral_analysis/spectral.py

[REVIEW] Fix stream usage for all functions

---

CHANGELOG.md
python/cusignal/acoustics/cepstrum.py
python/cusignal/convolution/convolve.py
python/cusignal/convolution/correlate.py
python/cusignal/filtering/resample.py
python/cusignal/spectral_analysis/spectral.py

closes https://github.com/rapidsai/cusignal/issues/125
Not gonna worry about the cp.stream issue in this PR. Can close the issue.

[REVIEW] Fix doc formatting for selected functions

---

CHANGELOG.md
docs/source/api.rst

Adding IO module for inclusion in Sphinx doc building (and for docs.rapids.ai to be updated)!

[REVIEW] Add IO module to cusignal docs

---

CHANGELOG.md
docs/source/api.rst
python/cusignal/__init__.py
python/cusignal/io/__init__.py
python/cusignal/io/_reader_cuda.py
python/cusignal/io/_writer_cuda.py
python/cusignal/io/reader.py
python/cusignal/io/writer.py
python/cusignal/utils/compile_kernels.py

Closes https://github.com/rapidsai/cusignal/issues/134
@mnicely -- we should probably file an issue to have pytests for the io functionality.

[REVIEW] Separate binary writer/pack and sigfm_writer from reader.py

---

CHANGELOG.md
conda/recipes/cusignal/build.sh
conda/recipes/cusignal/meta.yaml

This allows for `find_packages` to work properly.

[REVIEW] Packages cusginal properly

---

CHANGELOG.md
conda/environments/cusignal_base.yml
conda/environments/cusignal_full.yml
conda/environments/cusignal_jetson_base.yml
conda/recipes/cusignal/meta.yaml

Fixes https://github.com/rapidsai/cusignal/issues/140
Current hotfix to cap SciPy between versions 1.4 and 1.5.

[REVIEW] Fix missing six package on cusignal import

---

CHANGELOG.md
python/cusignal/spectral_analysis/spectral.py
python/cusignal/windows/windows.py

This PR fixes issue with `string_types` in SciPy 1.5.0
Fixes #145

[PR-REVIEW] Remove string_types dependency

---

ci/gpu/build.sh
conda/environments/cusignal_base.yml
conda/environments/cusignal_full.yml
conda/environments/cusignal_jetson_base.yml
conda/recipes/cusignal/meta.yaml

Backport of #143 
Depends on https://github.com/rapidsai/integration/pull/67

[HOTFIX] Fix missing six package on cusignal import [skip-ci-changelog]

---

CHANGELOG.md
CODE_OF_CONDUCT.md
README.md

All modifications to the README

[skip-ci] [REVIEW] Fix error in CoC, replace conda4aarch with miniforge, and add SciPy presentation

---

CHANGELOG.md
kalman_test_script.py
python/cusignal/estimation/filters.py

This adds documentation to KF based on https://github.com/rlabbe/filterpy/tree/master/filterpy.
Also, it fixes a bug I had when determine CuPy version.

[PR-REVIEW] Update kalman docs

---

CHANGELOG.md
kalman_test_script.py
python/cusignal/estimation/_filters_cuda.py
python/cusignal/estimation/filters.py

1. Fix debug print bug
2. Updates docs
3. Changes `update` inputs to match filterpy
4. Changes `predict` inputs to match filterpy
Not implemented is control matrix `B` arithmetic. This changes the size of the filter estimate. 
I need to think about how to implement this efficiently later.

[PR-REVIEW] Add functionality to KF

---

CHANGELOG.md
python/cusignal/convolution/convolve.py

fix typo in example plotting code

---

CONTRIBUTING.md
README.md
ci/checks/changelog.sh

Auto-merge triggered by push to `branch-0.15` that creates a PR to keep `branch-0.16` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.15 to branch-0.16 [skip ci]

---

ci/cpu/upload-anaconda.sh

Scripting somehow missed this before

[REVIEW] Remove master branch reference from upload anaconda script [skip-ci]

---

CHANGELOG.md
python/cusignal/estimation/_filters_cuda.py
python/cusignal/estimation/filters.py

This PR removes the requirement for CuPy v8 to utilize the Kalman Filter.
closes #205 
FYI @JasonAtNvidia

[REVIEW] CuPy 7.x to Kalman filter functionality

---

README.md

The purpose of this PR is to provide clarification on benchmarking in docs

[skip-ci] [REVIEW] Update README.md - (Benchmarking/Install)

---

CHANGELOG.md
python/cusignal/test/conftest.py
python/cusignal/test/test_convolution.py
python/cusignal/test/test_filter_design.py
python/cusignal/test/test_filtering.py
python/cusignal/test/test_spectral_analysis.py
python/cusignal/test/test_waveforms.py
python/cusignal/test/test_wavelets.py
python/cusignal/test/test_windows.py

Closes #220 
**Info**
This PR is to add synchronization to the existing cusignal tests

[REVIEW] Synchronization issue with cusignal testing

---

CHANGELOG.md
README.md

Added a section to explain SDR integration, highlighting SoapySDR and pyrtlsdr. Clean up language in Installation section to be more clear about the 'source' vs 'conda' install process.

[skip-ci] Update README to better explain SDR integration and Installation requirements

---

CHANGELOG.md
python/cusignal/convolution/convolve.py

Auto-merge triggered by push to `branch-0.16` that creates a PR to keep `branch-0.17` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.16 to branch-0.17 [skip ci]

---

CHANGELOG.md
python/cusignal/test/test_acoustics.py
python/cusignal/test/test_bsplines.py
python/cusignal/test/test_convolution.py
python/cusignal/test/test_filter_design.py
python/cusignal/test/test_filtering.py
python/cusignal/test/test_peak_finding.py
python/cusignal/test/test_spectral_analysis.py
python/cusignal/test/test_waveforms.py
python/cusignal/test/test_wavelets.py
python/cusignal/test/test_windows.py
python/cusignal/test/utils.py
python/cusignal/waveforms/waveforms.py

The PR adds functionality to our testing suites to allow for testing tuple outputs from cuSignal functions.

[REVIEW] ENH Increase robustness for testing

---

CHANGELOG.md

fix Branch 0.17 merge 0.16 conflixt [skip-ci-changelog]

---

CHANGELOG.md

Resolve auto-merger conflict in CHANGELOG.md

[skip-ci-changelog] Merge branch-0.16 into branch-0.17

---

CHANGELOG.md
README.md

Bump 0.15 to 0.16 and 0.16 nightly to 0.17 nightly

[skip-ci] [DOC] Update readme to reflect new version numbers

---

CHANGELOG.md
ci/checks/changelog.sh
ci/checks/style.sh
ci/cpu/build.sh
ci/cpu/upload.sh
ci/docs/build.sh
ci/gpu/build.sh
ci/gpu/test-notebooks.sh
ci/local/README.md
ci/release/update-version.sh

Auto-merge triggered by push to `branch-0.17` that creates a PR to keep `branch-0.18` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.17 to branch-0.18 [skip ci]

---

CHANGELOG.md

Fix Branch 0.18 merge 0.17

---

CHANGELOG.md
README.md
notebooks/E2E_Example.ipynb

Explicitly mention how GPU benchmarking typically works based on community feedback.

[REVIEW] [ENH] Clarify GPU timing in E2E Jupyter Notebook

---

README.md

Closes https://github.com/rapidsai/cusignal/issues/304
Thanks to @leofang for the hat tip!

[DOC] Update README to optimize CuPy build time on Jetson

---

README.md

Additional input from https://github.com/rapidsai/cusignal/issues/304

[DOC] Specify CuPy install time on Jetson Platform

---

docs/source/api.rst

Add pulse compression and pulse doppler functions to cuSignal documentation build.

Update cuSignal Documentation to Include Radar Functions

---

notebooks/api_guide/convolution_examples.ipynb

Closes https://github.com/rapidsai/cusignal/issues/303

Fix typo in convolution jupyter notebook example

---

.github/labeler.yml
CHANGELOG.md

This PR fixes the merge conflicts in #315.
Just a reminder that this PR should **not** be squash merged. Use a merge-commit instead.

Fix merge conflicts in #315

---

README.md

Auto-merge triggered by push to `branch-0.18` that creates a PR to keep `branch-0.19` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.18 to branch-0.19 [skip ci]

---

ci/gpu/test-notebooks.sh

Remove notebook from CI to unstick open PRs

Skip online signal processing tools testing

---

conda/recipes/cusignal/meta.yaml

Move minimum scipy version from 1.5 to 1.6 and minimum cupy version from 8.0 to 8.3.

Update min scipy and cupy versions

---

python/cusignal/__init__.py
python/cusignal/test/test_windows.py
python/cusignal/windows/__init__.py
python/cusignal/windows/windows.py

Forward-merge triggered by push to `branch-0.19` that creates a PR to keep `branch-0.20` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-0.19 to branch-0.20 [skip ci]

---

cpp/src/filtering/_sosfilt.cu

Fixed comment

---

python/cusignal/__init__.py
python/cusignal/test/test_waveforms.py
python/cusignal/waveforms/__init__.py
python/cusignal/waveforms/waveforms.py

Add sawtooth to waveforms
```bash
---------- benchmark 'Sawtooth': 4 tests -----------
Name (time in us)                     Mean          
----------------------------------------------------
test_sawtooth_gpu[0.5-16384]       26.4788 (1.0)    
test_sawtooth_gpu[0.25-16384]      26.8152 (1.01)   
test_sawtooth_cpu[0.5-16384]      494.6532 (18.68)  
test_sawtooth_cpu[0.25-16384]     500.5425 (18.90)  
----------------------------------------------------
```

Add sawtooth

---

conda/environments/cusignal_airt.yml
conda/environments/cusignal_base.yml
conda/environments/cusignal_full.yml
conda/environments/cusignal_jetson_base.yml

Remove conda defaults channel in dev environments

ENH Remove conda defaults channel in dev environments

---

CHANGELOG.md
conda/recipes/cusignal/meta.yaml

This PR fixes the merge conflicts in #374.

Fix merge conflicts [skip ci]

---

cpp/src/filtering/_upfirdn.cu
python/cusignal/filtering/_upfirdn_cuda.py
python/cusignal/filtering/filtering.py
python/cusignal/filtering/resample.py
python/cusignal/test/test_filtering.py

Forward-merge triggered by push to `branch-21.06` that creates a PR to keep `branch-21.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.06 to branch-21.08 [skip ci]

---

python/cusignal/radartools/radartools.py

Fixes issue where `ambgfun` was stripping imaginary values in some cases. 
closes #396

Fixed imaginary part being removed in delay mode of ambgfun

---

python/cusignal/filter_design/fir_filter_design.py

Closes https://github.com/rapidsai/cusignal/issues/399

fix firwin bug where fs is ignored if nyq provided

---

python/cusignal/__init__.py
python/cusignal/radartools/__init__.py
python/cusignal/radartools/beamformers.py

Need to confirm correct dimensions and usage. Perf looks good, but I'm sure there's places for optimization (including reduction of GEMMs with three separate calls).
Testing with:
```python
import cusignal
x = cp.random.randn(10, 1000000)
sv = cp.random.randn(10, 1)
w = cusignal.mvdr(x, sv)
```

[WIP] Adding MVDR (Capon) Beamformer

---

python/cusignal/radartools/beamformers.py

Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip ci]

---

python/cusignal/radartools/__init__.py
python/cusignal/radartools/radartools.py
python/cusignal/test/test_radartools.py

Added CFAR routines in 1d and 2d with some basic unit tests.

Adding CFAR

---

python/cusignal/filtering/_upfirdn_cuda.py

Change type check to use isinstance instead of str compare

---

docs/source/api.rst
python/cusignal/filtering/resample.py

Closes https://github.com/rapidsai/cusignal/issues/422 (I hope!)

Doc fix for FIR Filters

---

python/cusignal/wavelets/wavelets.py

The default data type for cp.empty() is "float". However, a complex output is expected for wavelet when using e.g. morlet2. Therefore, I change the data type to "complex128" at line 308 and also change the example at line 302 to visualize the magnitude of the complex wavelet coefficients.

[Improvement] Allow complex wavelet output for morlet2

---

python/cusignal/wavelets/wavelets.py

I found that the current cwt cannot work unless:
- At line 309, widths[0] will return a one-element array, which cannot be used as the input for wavelet. I change widths[0] to an integer 1 here since we only need to check the datatype regarding the wavelet.
- At line 317 and 318, the datatype of width should be forced to integer type. Such conversion is also used in the prior version.
I have tested these changes and the cwt function works.

[Review] Data type conversion for cwt.

---

docs/source/api.rst
python/cusignal/__init__.py
python/cusignal/demod/__init__.py
python/cusignal/demod/demod.py

Adding simple wrapper for FM demodulation

Add FM Demodulation to cuSignal

---

.github/PULL_REQUEST_TEMPLATE.md
conda/recipes/cusignal/meta.yaml
python/cusignal/filtering/filtering.py
python/cusignal/filtering/resample.py
python/cusignal/test/conftest.py
python/cusignal/test/test_filtering.py
python/cusignal/test/utils.py

Forward-merge triggered by push to `branch-22.02` that creates a PR to keep `branch-22.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.02 to branch-22.04 [skip gpuci]

---

python/cusignal/convolution/convolve.py
python/cusignal/peak_finding/peak_finding.py
python/cusignal/waveforms/waveforms.py

fixes https://github.com/rapidsai/cusignal/issues/457

[REVIEW][Doc] Fixes a list of minor errors in the example codes #457

---

notebooks/sdr/rtlsdr_offline_demod_to_transcript.ipynb
notebooks/sdr/sdr_wfm_demod.ipynb

- Adjusts the installation section for the RTL-SDR example notebook to properly install all of the NeMo ASR toolkit dependencies as well as SoapySDR with RTL-SDR support
- Installs pyaudio + SoapySDR with LimeSDR support for the general SDR example notebook
- Adds a disclaimer to both notebooks that they will not work without an SDR device connected
Closes #469 
Closes #470

Add/fix installation sections for SDR example notebooks

---

conda/recipes/cusignal/conda_build_config.yaml
conda/recipes/cusignal/meta.yaml

Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

---

conda/recipes/cusignal/meta.yaml

Reverts: https://github.com/rapidsai/cusignal/pull/494

Revert "Allow CuPy 11"

---

conda/recipes/cusignal/meta.yaml

This PR allows cupy 11.
xref: https://github.com/rapidsai/integration/pull/528

Allow cupy 11

---

CHANGELOG.md
conda/recipes/cusignal/meta.yaml
python/cusignal/filtering/resample.py

Forward-merge triggered by push to `branch-22.10` that creates a PR to keep `branch-22.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.10 to branch-22.12 [skip gpuci]

---

README.md

Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

---

README.md

Closes https://github.com/rapidsai/cusignal/issues/529

Fix broken TOC links in README

---

docs/source/conf.py

Fixes docs to mark NVIDIA as the author.

Fix documentation author

---

.pre-commit-config.yaml

Update isort version to 5.12.0

---

conda/recipes/cusignal/conda_build_config.yaml

This PR updates builds to use GCC 11.

Update to GCC 11

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cusignal/meta.yaml
dependencies.yaml
python/cusignal/peak_finding/peak_finding.py

Update cupy dependency

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cusignal/meta.yaml
dependencies.yaml
python/cusignal/convolution/_convolution_cuda.py

Forward-merge triggered by push to `branch-23.06` that creates a PR to keep `branch-23.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.06 to branch-23.08
