cusignal/signaltools.py
Uses np.convolve() for short/direct version convolutions. 
cusignal/test/test_signaltools.py::test_wiener[32768] PASSED                                                                         [ 18%]
cusignal/test/test_signaltools.py::test_wiener[16777216] PASSED                                                                      [ 19%]
Fixes https://github.com/rapidsai/cusignal/issues/3
=> Use np.convolve() for direct version convolutions

README.md
Adding Anaconda install directions for cuSignal for x86 architectures.
=> Add anaconda install instructions to README

CHANGELOG.md, python/cusignal/_upfirdn.py, python/cusignal/signaltools.py
This PR addresses recommendations by @mnicely to remove orphaned code targeting `int` support for upfirdn. This also adds documentation on the `use_numba` option in both `cusignal.upfirdn` and `cusignal.resample_poly`.
=> [REVIEW] upfirdn/resample_poly documentation update and code cleanup

CHANGELOG.md, python/cusignal/_upfirdn.py
~~I would like to determine why my Numba kernels are running so much slower than my CuPy kernels.~~
~~Using floats (Numba)~~
~~`# @cuda.jit(fastmath=True) # 38 registers - 157-190us`~~
~~`# @cuda.jit(void(float32[:], float32[:], int32, int32, int32, int32, int32, float32[:],), fastmath=True) # 48 registers - 160-190us`~~
~~`@cuda.jit(void(float32[:], float32[:], int64, int64, int64, int64, int64, float32[:],), fastmath=True) # 38 registers - 157-190us`~~
~~`def _numba_upfirdn_1d_float(x, h_trans_flip, up, down, x_shape_a, h_per_phase, padded_len, out):`~~
~~Using doubles (Numba)~~
~~`# @cuda.jit(fastmath=True) # 38 registers - 157-190us`~~
~~`# @cuda.jit(void(float64[:], float64[:], int32, int32, int32, int32, int32, float64[:],), fastmath=True) # 48 registers - 160-190us`~~ …
=> [REVIEW] Added streams and double/complex64/complex128 functionality

CHANGELOG.md, conda/recipes/cusignal/meta.yaml
Removes the conda test phase since importing cusignal now needs a GPU for JIT compilation.
=> [REVIEW] Remove conda test phase

CHANGELOG.md, python/cusignal/_signaltools.py, python/cusignal/signaltools.py
This set of changes enables filter coefficients to be reused across multiple calls to `cusignal.resample_poly()`. This is important for performance as re-creating the 
coefficient array and uploading it to the GPU each time can be expensive.
Several bugs were found and fixed along the way:
1) Input filter coefficients were supported but would be modified in-place.
2) Double-precision outputs would be produced even if both the input array and the filter coefficients were of lower precision. In practice, this made the float32 kernels never be called which was confirmed by examining `nvprof` traces.
=> [REVIEW] Fix multiple issues with resample_poly's prototype filter

CHANGELOG.md, python/cusignal/_upfirdn.py
1. Move x_shape_a, h_per_phase, and padded_len to apply_filter to remove redundant code
2. Move CuPy kernels from _init_cupy_upfirdn_1d_modules to module object.
This allows the cupy kernels to be compiled at import, and eliminates
compile at first call.
There's one limitation at the moment, a compile at import is not "device aware";
therefore, compiled code will reside in the CUDA context of the active device
during import
If the user were to target a new GPU, cupy.cuda.runtime.setDevice(X), where
X is a GPU device id, a crash will occur.
This error can be mitigated by re-importing after setDevice.
This mitigation will not be necessary when CuPy implements device awareness.
https://github.com/cupy/cupy/pull/3200
3. To minimize code due to multiple kernels, where possible, kernels will be …
=> [REVIEW] Implement CuPy kernels as module object and templating

CHANGELOG.md, python/cusignal/_upfirdn.py
The goal of this changeset is to unify how the backend calls both numba and cupy kernels and make it explicit what datatypes are supported in all cases.
Most of the differences between the numba and cupy APIs when creating a kernel are now in a single place, `_populate_kernel_cache()`, and the differences when invoking a kernel are mostly contained within `_get_backend_kernel()`.
Functional change:  The 2D numba kernels are now also jit-compiled at module import time for each supported data type and cached.
=> [REVIEW] Make upfirdn()'s kernel caching more generic, support 2D

CHANGELOG.md, README.md, python/cusignal/_upfirdn.py, python/cusignal/signaltools.py
This PR makes the following changes:
- Set `use_numba` default value from True to False
- The CuPy backend is only supported for 1D signals presently; if the user sets `use_numba=True` and inputs a 2D array, use Numba CUDA backend
- Update README to V100 updated stats for `resample_poly` and fix data type error
=> Disable Numba CUDA backend in upfirdn/resample_poly by default and update associated docs

CHANGELOG.md, docs/source/api.rst
Closes https://github.com/rapidsai/cusignal/issues/12
This hot fix PR adjusts the `api.rst` in the cuSignal docs to include:
* waveforms
* fir_filter_design
* windows
* spectral
* acoustics
* wavelets
* bsplines
=> [REVIEW] Expansion of Docs to include all modules

CHANGELOG.md, python/cusignal/signaltools.py
The original `resample` function receives a time-domain signal and converts it to the frequency domain to perform the resampling. This pull request proposes to add an option to pass a signal in the frequency domain format. This will reduce the computational load of workloads that require several resamples of the same signal. If the function is called with the `fft` option set to `True` it will skip the `fft` function.
=> Add frequency domain input option to the Resample function

CHANGELOG.md, python/cusignal/test/test_wavelets.py, python/cusignal/test/test_windows.py
NOTE: I think a have a different black formatter configuration causing a few differences.
In `test_wavelets.py`, modifed `test_ricker`
Change
```
@pytest.mark.parametrize('num_samps', [2**14])
@pytest.mark.parametrize('a', [10, 1000])
def test_ricker(num_samps, a):
cpu_window = signal.morlet(num_samps)
gpu_window = cp.asnumpy(cusignal.morlet(num_samps))
assert array_equal(cpu_window, gpu_window)
```
to 
```
@pytest.mark.parametrize("num_samps", [2 ** 14])
@pytest.mark.parametrize("a", [10, 1000])
def test_ricker(num_samps, a):
cpu_window = signal.ricker(num_samps, a)
gpu_window = cp.asnumpy(cusignal.ricker(num_samps, a))
assert array_equal(cpu_window, gpu_window)
```
In `test_waveforms.py, modified `test_gaussian` and `test_general_gaussian`
```
@pytest.mark.parametrize('num_samps', …
```
=> [REVIEW] Fixed errors in test_wavelets and test_windows

CHANGELOG.md, python/cusignal/_signaltools.py
This PR does the following
1. Refactor `_signaltools.py` to utilize the new Numba/CuPy framework we added in `_upfirdn.py`. This will allow us to added CuPy kernels next
2. With (1), added type specialization to all Numba kernels
3. Reduces the number of registers per kernel from 64 to 32.
=> [REVIEW] Refactor _signaltools.py to new Numba/CuPy framework.

CHANGELOG.md, python/cusignal/_signaltools.py, python/cusignal/benchmark/bench_signaltools.py, python/cusignal/signaltools.py, python/cusignal/test/test_signaltools.py
This PR does the following
1. Updates **correlate2d** and **convolve2d** in `signaltools.py` to accept _cp_stream_ and _use_numba_ arguments.
2. Updates bench_correlate2d_gpu and bench_convolve2d_gpu in `bench_signaltools.py` to accept _use_numba_ arguments.
3. Updates `_signaltools.py` to utilizes cupy.pad(symm/wrap) versus numpy.pad(symm/wrap), which was not available during initial development. Up to 20x-30x performance improvement to large test cases by eliminated data transfers.
4. Updates Numba kernel indexing to match CuPy raw kernel indexing. Indexing in 2d making much more sense now.
5. Finally, CuPy raw kernels and framework have been added to `_signaltools.py`.
Below are benchmark results using `pytest -v --benchmark-only -k "2d"`. There are 116 tests performed. The takeaway is …
=> [REVIEW] Added CuPy raw kernels for correlate2d and convolve2d

CHANGELOG.md, python/cusignal/__init__.py, python/cusignal/signaltools.py, python/cusignal/test/test_signaltools.py
Closes https://github.com/rapidsai/cusignal/issues/47
This PR adds `decimate` support for FIR filters. IIR filters are still not yet supported. This PR leverages the recent improvements to `resample_poly` and `upfirdn` (raw CuPy CUDA kernels, CUDA streams, etc).
I've added a decimate test to the pytests as well, but we may benefit from some more performance benchmarking.
CC @boonedoggle
=> [REVIEW] Addition of decimation for FIR ftypes

CHANGELOG.md, README.md
This PR updates the `README` to fall inline with [cuDF](https://github.com/rapidsai/cudf). Now that RAPIDS has official Docker/Conda packaging, the README was updated to reflect these instructions. A list of changes:
* Added explicit conda install instructions
* Added Docker install instructions
* Updated dependencies to focus on optional packages
* Added blurb about raw cupy cuda kernels
=> [REVIEW] Update README - Reorganize Install Instructions

CHANGELOG.md, python/cusignal/_spectral.py, python/cusignal/benchmark/bench_signaltools.py, python/cusignal/benchmark/bench_spectral.py, python/cusignal/benchmark/conftest.py, python/cusignal/spectral.py, python/cusignal/test/test_spectral.py
Recently noticed we didn't have any tests or benchmarks for `cusignal.lombscargle`
This PR does the following
1. Updates `test_spectral.py` to include `test_lombscargle`
2. Updates `bench_spectral.py to include `BenchLombScargle`
3. Updates `_spectral.py` to new Numba/CuPy framework
4. Combine **_lombscargle()** and **_lombscargle_norm()** into one Numba kernel - **_numba_lombscargle()**
5. Adds CuPy Module **_cupy_lombscargle()**
6. Renames **resample_data_gen** in `conftest.py` to **linspace_data_gen**.
Note: Only float64 is implemented in Numba/CuPy kernels because **lombscargle()** in `spectral.py` is creating float64 arrays
Benchmarks show `cusignal.lombscargle` Numba/CuPy kernels are ~1600x/~7900x faster, respectively, than `signal.lombscargle`, for large test cases.
```bash …
```
=> [REVIEW] Added CuPy for lombscargle, along with tests/benchmarks

CHANGELOG.md, notebooks/api_guide/acoustics_examples.ipynb, notebooks/api_guide/bspline_examples.ipynb, notebooks/api_guide/peak_finding_examples.ipynb, notebooks/api_guide/signaltools_examples.ipynb, notebooks/api_guide/spectral_examples.ipynb, notebooks/api_guide/waveform_examples.ipynb, notebooks/api_guide/wavelets_examples.ipynb, notebooks/api_guide/windows_examples.ipynb
This PR updates the timing in the `notebooks\api` notebooks and shows:
* Numba vs Raw CuPy CUDA Kernel performance for `resample_poly`, `correlate2d`, `convolve2d`
* Update `%%time` to `%%timeit` to provide better performance characterizations
* Show API usage for new `decimate` function
=> [REVIEW] Update API Guide Notebooks

CHANGELOG.md, python/cusignal/_signaltools.py, python/cusignal/_upfirdn.py
https://github.com/numba/numba/pull/5197 refactors many of Numba's submodules. Mirror the required import changes in cusignal.
This keeps cusignal in sync with numba master and the 0.49 release candidate but breaks compatibility with the current numba release (0.48).
This should go in eventually but also needs to make sure we keep compatibility with whatever version of numba we're getting in the conda channels selected by our packaging (and certainly updates the minimum required version) - need help with this part.
=> [REVIEW] Use Numba 0.49+ API where required

CHANGELOG.md, python/cusignal/_signaltools.py, python/cusignal/benchmark/bench_signaltools.py, python/cusignal/signaltools.py, python/cusignal/test/test_signaltools.py
This PR statifies feature request https://github.com/rapidsai/cusignal/issues/57, by adding 1D **correlate** and **convolve** to `_signaltools.py`. They are only implemented with CuPy kernels, not Numba. They are active when `method='direct'`
It also adds appropriate tests and benchmarks.
**This PR is not implemented on the framework introduced in PR https://github.com/rapidsai/cusignal/pull/56. This PR should be merged first!**
Benchmarks show speedups from **10x** - **890x**.
Notice that [direct-valid-32768-32768] provides the best time. Not sure what NumPy is doing, but investigation is need to determine if it is something we can implement as well.
```bash
------------------------------------------------------------------------------------------------------- benchmark 'Convolve': 54 …
```
=> [REVIEW] Added CuPy kernels for correlate1d/convolve1d

CHANGELOG.md, python/cusignal/_signaltools.py, python/cusignal/_spectral.py, python/cusignal/_upfirdn.py, python/cusignal/benchmark/bench_signaltools.py, python/cusignal/signaltools.py, python/cusignal/test/test_signaltools.py
This PR is meant to address Issue https://github.com/rapidsai/cusignal/issues/54, where import time for cusignal is excessive long because all Numba and CuPy kernel are being compile during import.
This PR attempts to solve this issue by allowing users the ability to explicitly precompile desired Numba or CuPy kernel before usage and also allow kernel to be compile on first use.
Currently, this PR focuses on **cusignal.lombscargle** in `_spectral.py` as a testbed. 
1. Remove **_populate_kernel_cache()** from being called on import and move it to **_lombscargle**. This will allow kernels of a specific _dtype_ and _use_numba_ to be compiled on first use. **_populate_kernel_cache()** will now verify if a kernel has already been compiled. If yes, return; if no, compile desired kernel. …
=> [REVIEW] Remove compile penalty during import

CHANGELOG.md, python/cusignal/_signaltools.py, python/cusignal/_spectral.py, python/cusignal/_upfirdn.py
This PR add deprecation warnings to Numba kernel selections.
Current message is 
> FutureWarning: Numba kernels will be removed in a later release
Also, this PR fixes the stack level for **upfirdn2d** warning to show proper warning location.
```bash
/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cusignal-0.14.0a0+194.g9949e1d.dirty-py3.8.egg/cusignal/_upfirdn.py:348: UserWarning: CuPy backend is only implemented for ndim == 1                 Running with Numba CUDA backend
warnings.warn(
```
changed to
```bash
upfirdn2d.py:61: UserWarning: CuPy backend is only implemented for ndim == 1:
***Running with Numba CUDA backend***
gpu = cusignal.upfirdn(h, x, 2, 3, axis=axis)
```
```bash
upfirdn2d.py:31: FutureWarning: Numba kernels will be removed in a later release
gpu = …
```
=> [REVIEW] Added warning for Numba kernel deprecation

CHANGELOG.md, docs/source/api.rst
Hotfix to address various sections of the updated docs failing to build.
=> [REVIEW] Fix Typo that Prevented Docs from Building

CHANGELOG.md, ci/local/README.md, ci/local/build.sh
This script is designed for developer and contributor use. This tool mimics the actions of gpuCI on your local machine. This allows you to test and even debug your code inside a gpuCI base container before pushing your code as a GitHub commit. The script can be helpful in locally triaging and debugging RAPIDS continuous integration failures.
=> Local gpuCI build script

CHANGELOG.md, python/cusignal/_lfilter.py, python/cusignal/benchmark/bench_signaltools.py, python/cusignal/filtering/filtering.py, python/cusignal/test/test_signaltools.py
This PR ports @luigifreitas lfilter implementation to a CuPy raw kernel
Pre-CuPy 
```bash
---------------------------------------------------------------------------------------------------- benchmark 'Lfilter': 2 tests ----------------------------------------------------------------------------------------------------
Name (time in us)                       Min                       Max                      Mean                 StdDev                    Median                     IQR            Outliers         OPS            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> [REVIEW] cusignal.lfilter implementation

CHANGELOG.md, python/cusignal/_lfilter.py, python/cusignal/_signaltools.py, python/cusignal/_spectral.py, python/cusignal/_upfirdn.py, python/cusignal/convolution/__init__.py, python/cusignal/convolution/convolve.py, python/cusignal/convolution/correlate.py, python/cusignal/filtering/__init__.py, python/cusignal/filtering/filtering.py, python/cusignal/filtering/resample.py, python/cusignal/spectral_analysis/__init__.py, python/cusignal/spectral_analysis/spectral.py
This PR implements auto-synchronization for all CuPy/Numba kernels by default. This will clear up some usage confusion and fix a bug with our pytest-benchmark results.
The following parameter has been added to all public facing API calls.
`autosync=True,`
If the API call, before `return` the following lines have been added.
```python
if autosync is True:
cp_stream.synchronize()
```
If `autosync=False` is passed, once the CuPy/Numba kernel has launched control flow will return to the host code. The device and host code can be sync manually with the following command
`cp_stream.synchronize()`, where `cp_stream = cp.cuda.stream.Stream(null=True)`.
The results can be verified with pytest-benchmarks. If we look at _lombscargle_gpu_ for example. Notice with `autosync` the min, mean, and median …
=> [REVIEW] Autosync functionality

.gitattributes, CHANGELOG.md
cuSignal is classified on GitHub as a collection of Jupyter Notebooks. Adding the `linguist-vendored` option into `*.ipynb` to ignore the notebooks from GitHub stats.
=> [REVIEW] Add git attributes to remove notebooks from stats

CHANGELOG.md, python/cusignal/utils/compile_kernels.py
During the code refactor I moved the data type check to `_validate_input` which only checks data type during kernel precompile. This left a bug during runtime allowing users to pass incompatible data types causing a crash. I moved the following code back to `_populate_kernel_cache`, now code gets checked on both paths.
```python
try:
numba_type, c_type = SUPPORTED_TYPES[np_type]
except KeyError:
raise KeyError(
"Datatype {} not found for '{}'".format(np_type, k_type.value)
)
```
=> [REVIEW] Fix code refactor bug

CHANGELOG.md, README.md, conda/environments/cusignal_base.yml, conda/environments/cusignal_full.yml, conda/environments/cusignal_jetson_base.yml
Closes https://github.com/rapidsai/cusignal/issues/94
* Add pytest-benchmark
* Update conda env name from cusignal to cusignal-dev
=> [REVIEW] Add pytest-benchmark to Conda environment files and clarify dev naming

CHANGELOG.md, python/cusignal/__init__.py, python/cusignal/benchmark/bench_signaltools.py, python/cusignal/filter_design/filter_design_utils.py, python/cusignal/filtering/_sosfilt_cuda.py, python/cusignal/filtering/filtering.py, python/cusignal/filtering/resample.py, python/cusignal/test/test_signaltools.py, python/cusignal/utils/compile_kernels.py
Scaffolding code for our `sosfilt` implementation. A few things here:
* `sosfilt` placed in `filtering/filtering.py`
* added `filter_design_utils.py` in `filter_design` for sos structure validation
* Added `sosfilt` Python code (to be moved to Numba/CuPy CUDA) in `filtering/_sosfilt_cuda.py`
* Updated documentation for sosfilt. @mnicely -- the example listed in the doc should serve as a good test case. I've pasted it below, too:
```python
from scipy import signal
import cusignal
sos = signal.ellip(13, 0.009, 80, 0.05, output='sos')
sos = cp.asarray(sos)
x = cp.random.randn(100_000_000)
y = cusignal.sosfilt(sos, x)
```
To-do:
I'm going to target this for 0.15 but think the algorithm is straighforward enough to get into 0.14.
closes …
=> [WIP] Implementation of `sosfilt` as an alternative to `lfilter`

CHANGELOG.md, ci/gpu/build.sh
Install dependencies via `rapids-build-env` (which is pre-installed in the containers).
This brings the repo in line with https://docs.rapids.ai/maintainers/depmgmt/
Depends on https://github.com/rapidsai/integration/pull/49
=> [REVIEW] Install dependencies via meta package

CHANGELOG.md, python/cusignal/filtering/_upfirdn_cuda.py, python/cusignal/test/test_signaltools.py
This PR is to fix #137 , where an overflow issue occurs in the `_cupy_upfirdn_1d()` function.
The fix consists of using `size_t` over `int`.
Adding tests as well.
This only fixes the CuPy raw kernel in 0.15.
=> [PR-REVIEW] Fix overflow issues in upfirdn

CHANGELOG.md, notebooks/api_guide/io_examples.ipynb
Adding a new `api_guide` Jupyter notebook to demonstrate how to GPU accelerate SigMF/binary data reads with cuSignal. 
To-Do
=> [REVIEW] Add Jupyter Notebook to Show I/O Usage

CHANGELOG.md, conda/environments/cusignal_airt.yml
Added AIR-T conda recipe so that cuSignal officially support the AIR_T
=> [REVIEW] Added AIR-T conda recipe so that cuSignal officially support the AIR_T

CHANGELOG.md, python/cusignal/filtering/filtering.py
closes https://github.com/rapidsai/cusignal/issues/151
Using numpy's `r_` functionality to calculate new array dimensions. Since this is an 'array setup' operation, I don't anticipate a major performance hit here.
=> [REVIEW] Fix bug in detrend calculation due to NotImplementedError with array slicing in cupy's r_ functionality

CHANGELOG.md, kalman_test_script.py, python/cusignal/convolution/_convolution_cuda.py, python/cusignal/estimation/filters.py, python/cusignal/filtering/_sosfilt_cuda.py, python/cusignal/filtering/_upfirdn_cuda.py, python/cusignal/io/_reader_cuda.py, python/cusignal/io/_writer_cuda.py, python/cusignal/spectral_analysis/_spectral_cuda.py, python/cusignal/utils/arraytools.py, python/cusignal/utils/debugtools.py
This PR adds logic to print debug information on CuPy RawKernel if an environment variable is set.
Added logic to `debugtools.py`
```python
def print_atts(func):
if "CUSIGNAL_DEV_DEBUG" in os.environ:
print("name:", func.kernel.name)
print("max_threads_per_block:", func.kernel.max_threads_per_block)
print("num_regs:", func.kernel.num_regs)
print(
"max_dynamic_shared_size_bytes:",
func.kernel.max_dynamic_shared_size_bytes,
)
print("shared_size_bytes:", func.kernel.shared_size_bytes)
print(
"preferred_shared_memory_carveout:",
func.kernel.preferred_shared_memory_carveout,
)
print("const_size_bytes:", func.kernel.const_size_bytes)
print("local_size_bytes:", func.kernel.local_size_bytes)
print("ptx_version:", func.kernel.ptx_version)
print("binary_version:", func.kernel.binary_version) …
```
=> [PR-REVIEW] Add debugging environment variable

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
This PR changes any 'master' references to 'main' in markdown files throughout the repo as part of the new 'master' to 'main' branch migration.
=> [skip ci] Update master references for main branch

CHANGELOG.md, python/cusignal/convolution/convolve.py, python/cusignal/convolution/correlate.py, python/cusignal/filter_design/fir_filter_design.py, python/cusignal/filtering/resample.py, python/cusignal/peak_finding/peak_finding.py, python/cusignal/windows/windows.py
I went through the docs and updated references to scipy signal, np and typecasting for plotting.
A few problems remained:
- Example code for using welch with `median`
- Coherence example code tries to use `butter` method, which doesn't exist
- Parzen window tries to use `extract` method of `cupy`
- I didn't address formatting, which is a mess for some functions here: https://docs.rapids.ai/api/cusignal/stable/api.html#cusignal.convolution.convolve.convolve2d
=> [REVIEW] fix typos in example code in docs

CHANGELOG.md, python/cusignal/convolution/correlate.py, python/cusignal/estimation/filters.py, python/cusignal/windows/windows.py
This PR fixes a bug found by @JasonAtNVIDIA.
If CuPy was not installed by source, say like `pip install cupy-cuda102` the version returned by `pkg_resources` didn't return **cupy**.
New version check
```python
ver = cp.__version__
if (
ver != "8.0.0b4"
and ver != "8.0.0b5"
and ver != "8.0.0rc1"
and ver != "8.0.0"
):
raise NotImplementedError(
"Kalman Filter only compatible with CuPy v.8.0.0b4+"
)
```
Per the comment, CuPy v8.0 should be officially release before cuSignal 0.16. In cuSignal 0.16, for KalmanFilter, minimal CuPy will be force to v.8.0.0.
=> [PR-REVIEW] Fix KF version check bug

CHANGELOG.md, conda/recipes/cusignal/meta.yaml
Don't include CuPy 8.0 in Conda recipe to fix cuSignal build error.
=> [REVIEW] Fix build error with cupy 8.0dev

CHANGELOG.md, python/cusignal/__init__.py, python/cusignal/utils/__init__.py, python/cusignal/utils/arraytools.py
Community requested. If a user wants to integrate existing PyCUDA code into cuSignal, this new `cusignal.from_pycuda` function will return a cupy `ndarray`.
Example usage:
```python
import pycuda.gpuarray as gpuarray
import pycuda.driver as cuda
import pycuda.autoinit
import numpy as np
pycuda_arr = gpuarray.to_gpu(np.random.randn(10).astype(np.float32))
cupy_arr = cusignal.from_pycuda(pycuda_arr)
print(pycuda_arr.ptr)
print(cupy_arr.__cuda_array_interface__['data']
```
=> [REVIEW] Add connection to PyCUDA gpuarray

ci/checks/changelog.sh
This PR removes unecessary references to master or updates references to the new main branch in CI scripts and other OPS-owned files.
=> [REVIEW] Update CI scripts to remove references to master [skip ci] 

ci/checks/changelog.sh
Auto-merge triggered by push to `branch-0.15` that creates a PR to keep `branch-0.16` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> [gpuCI] Auto-merge branch-0.15 to branch-0.16 [skip ci]

CHANGELOG.md, docs/source/api.rst, python/cusignal/__init__.py, python/cusignal/filtering/__init__.py, python/cusignal/filtering/filtering.py
`cusignal.filtering` contained 2 separate polyphase channelizers: one CPU version and other GPU. I've removed the legacy CPU only version and renamed `cusignal.filtering.channelize_poly_gpu` to `cusignal.filtering.channelize_poly`. This is a GPU library, so all functions are assumed to run on GPU without the explicit API specification!
I also noticed that the polyphase channelizer and firfilter weren't specifically included in the cuSignal documentation. I've added this.
=> [REVIEW] Rename channelize_poly_gpu to channelize_poly and remove CPU only version; Update documentation

CHANGELOG.md, cpp/src/filtering/_channelizer.cu, python/cusignal/filtering/_channelizer_cuda.py, python/cusignal/filtering/filtering.py
This PR fixes a bug in channelizer and reduces the shared memory by 50%
1. Reduce shared memory
- Because data copied from shared memory to a register before reduce operation. We can do it manually for `h` and reuse `s_mem` for `reg`
2. Bug
- The wrong stride was chosen for the grid-stride loop causing more work to be done.
```bash
Generating CUDA Kernel Statistics...
CUDA Kernel Statistics (nanoseconds)
Time(%)      Total Time   Instances         Average         Minimum         Maximum  Name …
```
=> [REVIEW] Fix bug in channelizer

CHANGELOG.md, python/cusignal/filtering/filtering.py
Need to add a whitespace before the closing function description to correctly render sphinx docs.
=> [REVIEW] Fix formatting in Docs build

CHANGELOG.md, docs/source/api.rst
rapids.ai documentation previously lacked an estimation section.
=> [REVIEW] Add KF to docs

CHANGELOG.md, python/cusignal/test/test_windows.py, python/cusignal/windows/__init__.py, python/cusignal/windows/windows.py
This PR will reevaluate performance of all window functions implementations.
As an example, *chebwin* was performing multiple operations on scalars and array slicing.
Below is a screenshot from Systems. There are 76 API calls
Moving scalar operations to the CPU and combining multiple arithmetic operations with a CuPy ElementwiseKernel, the number of call is reduced to 14, all memcpys are elimination and the performance in increased by roughly 4x.
=> [REVIEW] Improve Window functions performance

CHANGELOG.md, python/cusignal/convolution/convolution_utils.py, python/cusignal/convolution/convolve.py, python/cusignal/test/conftest.py, python/cusignal/test/test_wavelets.py, python/cusignal/utils/fftpack_helper.py, python/cusignal/wavelets/__init__.py, python/cusignal/wavelets/wavelets.py, python/cusignal/windows/__init__.py
Closes #223 
Closes #234 
This PR improves performance for all wavelets functions.
```bash
-------------- benchmark 'CWT': 4 tests --------------
Name (time in ms, mem in bytes)         Mean          
------------------------------------------------------
test_cwt_gpu[31-16384]               72.6608 (5.04)   
test_cwt_gpu[127-16384]             310.6303 (21.54)  
------------------------------------------------------
---------- benchmark 'CWTComplex': 4 tests -----------
Name (time in ms, mem in bytes)         Mean          
------------------------------------------------------
test_cwt_complex_gpu[31-16384]       71.0334 (3.05)   
test_cwt_complex_gpu[127-16384]     300.4632 (12.91)  
------------------------------------------------------
------------ benchmark 'Morlet': 2 tests …
```
=> [REVIEW] Improve Wavelets functions performance

CHANGELOG.md, build.sh, conda/recipes/cusignal/build.sh, conda/recipes/cusignal/meta.yaml
This PR updates cusignal's conda recipe `build.sh` file to use the `build.sh` file in the project's root directory. This fixes an issue where the `fatbin` files were not being generated for conda package uploads.
I also updated `conda/recipes/cusignal/meta.yaml` to use `path` instead of `git_url`. The differences are outlined in the excerpt below from the conda docs ([src](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#source-from-a-local-path)):
> "If the local path is a git or svn repository, you get the corresponding environment variables defined in your build environment. The only practical difference between git_url or hg_url and path as source arguments is that git_url and hg_url would be clones of a repository, while path would be a copy of the …
=> Update conda build files

CHANGELOG.md, python/cusignal/peak_finding/peak_finding.py, python/cusignal/test/test_peak_finding.py
Closes #238 
This PR currently provides a quick fix for clipping. The idea is to do clipping manually because it is not native to `cupy.take`
```bash
(cusignal) belt@orion:~/workStuff/rapids/cusignal$ pytest python -v --benchmark-enable --benchmark-columns=mean -k TestPeakFinding
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1 -- /home/belt/anaconda3/envs/cusignal/bin/python
cachedir: .pytest_cache
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=True min_rounds=25 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=True warmup_iterations=10)
rootdir: …
```
=> [Review] Clipping fix for Peak Finding module

CHANGELOG.md, notebooks/E2E_Example.ipynb
A user of our Docker images recently opened up issue https://github.com/rapidsai/docker/issues/74 which states that PyTorch is not installed in our containers and therefore the `E2E_Example.ipynb` notebook cannot be successfully run from top to bottom. After speaking with @mike-wendt, he mentioned that we intentionally exclude PyTorch due to its size. Mike recommended adding a disclaimer to the notebook similar to the one introduced in this PR.
=> Add pytorch installation disclaimer to E2E_Example Notebook

CHANGELOG.md, cpp/src/filtering/_channelizer.cu, python/cusignal/filtering/filtering.py
This PR fixes the following:
1. A race condition in shared memory caused by a large grid stride.
2. Adds more keys to fft plan cache to ensure uniqueness.
=> [REVIEW] Fix channelizer bugs

CHANGELOG.md, python/cusignal/convolution/convolve.py
Closes #253 
This PR adds a check for CuPy v7 or v8, and uses version 8's internal FFT cache.
```bash
Without cache + CuPy v7.8
-------------------------------------------------------------------------------- benchmark 'FFTConvolve': 3 tests --------------------------------------------------------------------------------
Name (time in ms)                        Min               Max              Mean            StdDev            Median               IQR            Outliers       OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_fftconvolve_gpu[same-32768]      0.9265 (1.0)      2.3050 (1.37)     1.0593 (1.0) …
```
=> [REVIEW] Use CuPy v8 FFT cache plan

CHANGELOG.md, conda/recipes/cusignal/meta.yaml
Now that CuPy 8.0 is out, we need to bump our top-requirement beyond 8.0.0a... otherwise, cuSignal will pull in CuPy 7.8 as a dependency.
=> [REVIEW] Support cupy 8.0 and beyond in conda builds

CHANGELOG.md, conda/recipes/cusignal/meta.yaml
Auto-merge triggered by push to `branch-0.16` that creates a PR to keep `branch-0.17` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> [gpuCI] Auto-merge branch-0.16 to branch-0.17 [skip ci]

CHANGELOG.md, ci/gpu/build.sh
Current functionality does not actually properly handle errors in testing the notebooks.
${WORKSPACE}/ci/gpu/test-notebooks.sh 2>&1 | tee nbtest.log
Will only error if the last command in the pipe errors.
set +e -Eo pipefail will allow us to detect errors earlier in the pipe and hold the EXITCODE till we need it.
=> [REVIEW] FIX Fix notebook error handling in gpuCI

CHANGELOG.md, python/cusignal/test/test_waveforms.py, python/cusignal/waveforms/waveforms.py
This PR attempts optimize the waveform module
```bash
---------- benchmark 'Square': 4 tests -----------4)
Name (time in us)                   Mean          
--------------------------------------------------
test_square_gpu[0.5-16384]       32.3753 (1.0)    
test_square_gpu[0.25-16384]      33.0561 (1.02)   
test_square_cpu[0.5-16384]      251.2782 (7.76)   
test_square_cpu[0.25-16384]     254.5398 (7.86)
--------------------------------------------------
```
```bash
---------- benchmark 'Square': 4 tests -----------4)
Name (time in us)                   Mean          
--------------------------------------------------
test_square_cpu[0.25-16384]     257.9543 (1.0)    
test_square_cpu[0.5-16384]      260.2890 (1.01)   
test_square_gpu[0.25-16384]     466.7852 (1.81) …
```
=> [REVIEW] Optimize waveforms

CHANGELOG.md, notebooks/api_guide/io_examples.ipynb
`precompile_kernels` has been deprecated in cuSignal.
=> [REVIEW] Remove precompile_kernels from io_examples

CHANGELOG.md, ci/cpu/upload.sh
This PR updates an erroneous path in our CI build scripts.
=> Update conda upload script

CHANGELOG.md, cpp/src/convolution/_convolution.cu, python/cusignal/__init__.py, python/cusignal/convolution/__init__.py, python/cusignal/convolution/_convolution_cuda.py, python/cusignal/convolution/convolve.py
…eded={tests,validations,benchmarks,optimizations}
=> [REVIEW] Implemented convolve1d{2/3}o 'valid', needed={tests,benchmarks,optimizations}

CHANGELOG.md, notebooks/E2E_Example.ipynb
This PR updates the `conda install` command to include the `-y` flag in order to install PyTorch without requiring user input.
=> [skip-ci] Add `-y` flag to conda install in E2E_Example Notebook

CHANGELOG.md, README.md
Bump Python 3.7 to 3.8 and cuSignal 0.16 to 0.17.
=> Bump cuSignal Version

.github/labeler.yml
PR #299 added a new GitHub Action that had some invalid YAML. This PR fixes it.
According to the GitHub Action docs, any YAML values that start with `*` must be quoted to avoid problem ([src](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)).
=> Fix labeler.yml GitHub Action [skip-ci]

notebooks/api_guide/radar_examples.ipynb, python/cusignal/__init__.py, python/cusignal/radartools/__init__.py, python/cusignal/radartools/radartools.py
Adding a radar/phased array module scaffolding to later include common radar signal processing routines (pulse compression, doppler processing, beamforming, CFAR, etc). This current PR adds support for pulse compression.
=> [REVIEW] Include scaffolding for new radar/phased array module and add new pulse compression feature

notebooks/api_guide/radar_examples.ipynb, python/cusignal/__init__.py, python/cusignal/radartools/__init__.py, python/cusignal/radartools/radartools.py
**This PR should be merged after https://github.com/rapidsai/cusignal/pull/300**
Expanding on phased array processing tools, the pulse doppler processing function transforms a data-matrix that's slow-time (pulses) by fast time (range) to doppler by fast time (range). Pulse doppler processing helps remove background clutter and to detect phase shifts. 
In a row-major view (default for cuSignal), this consists of taking the FFT along the slow-time (pulse) dimension. In this case, we perform 1D FFTs along each column of the input data matrix.
=> [REVIEW] Add Pulse-Doppler Processing to radartools

docs/source/api.rst
Fix mistake in radar api docs where individual functions were treated as modules.
=> Fix Radar API Docs

CHANGELOG.md, docs/source/api.rst
Auto-merge triggered by push to `branch-0.18` that creates a PR to keep `branch-0.19` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> [gpuCI] Auto-merge branch-0.18 to branch-0.19 [skip ci]

README.md
Adds instructions on how to build cuSignal on Windows OS with WSL. Confirmed working by @mnicely. Clarifies https://github.com/rapidsai/cusignal/issues?q=is%3Aissue+is%3Aclosed.
=> Add WSL instructions for cuSignal Windows Builds

conda/recipes/cusignal/meta.yaml
Allow for CuPy 9.0 when available on conda channels.
=> Increment Max CuPy Version in CI

python/cusignal/waveforms/waveforms.py
Remove dependency on six in `waveforms.py` - no longer needed as we are only supporting Python 3 and above.
=> Remove six dependency

python/cusignal/io/reader.py
cuSignal's binary reader would ignore specified dtype, causing an error in parsing a stored binary file. The following code example now produces output `y` that matches input `x`.
```python
import cusignal
x = cp.arange(1000,dtype=cp.float32)
cusignal.write_bin('bintest',x)
y = cusignal.read_bin('bintest',dtype=cp.float32)
```
=> Fix bug in bin_reader that ignored dtype

cpp/src/filtering/_upfirdn.cu, python/cusignal/filtering/_upfirdn_cuda.py, python/cusignal/filtering/resample.py, python/cusignal/test/test_filtering.py, python/cusignal/utils/helper_tools.py
closes bug #295 
This code adds 2d grid stride looping to _cupy_upfirdn2D. This fixes the bug by removing the hardware cap on grid size in the y direction.
=> Add 2D grid-stride loop to fix BUG 295

python/cusignal/convolution/_convolution_cuda.py
Bug fix when looking at A100 optimization of `cusignal.convolve.`
Changed `cupy.array` to `cupy.asarray`.
Prior to PR:
```python
import cusignal
sig = cp.random.randn(16384000, dtype=cp.float32)
win = cp.random.randn(128, dtype=cp.float32)
%%timeit
cusignal.convolve(sig, win, mode='same', method='direct')
```
Runs in 1.22 ms on A100
After PR, the same code finishes in 1.12ms on A100
=> Fix bug in casting array to cupy

python/cusignal/__init__.py, python/cusignal/test/test_windows.py, python/cusignal/windows/__init__.py, python/cusignal/windows/windows.py
Taylor Windows was added to SciPy Signal in 1.6.x
This PR adds it to cuSignal.
Results on Titan RTX
```bash
-------------- benchmark 'Taylor': 8 tests ---------------
Name (time in us)                           Mean          
----------------------------------------------------------
test_taylor_gpu[False-20-32768]         567.8799 (1.0)    
test_taylor_gpu[True-20-32768]          694.2484 (1.22)   
test_taylor_gpu[False-100-32768]      2,703.1287 (4.76)   
test_taylor_gpu[True-100-32768]       3,139.7567 (5.53)   
test_taylor_cpu[False-20-32768]       6,314.9267 (11.12)  
test_taylor_cpu[True-20-32768]        7,083.8202 (12.47)  
test_taylor_cpu[True-100-32768]      37,077.0545 (65.29)  
test_taylor_cpu[False-100-32768]     37,368.7508 (65.80) …
```
=> Add Taylor window

docker/Dockerfile
Support users who would like to install cuSignal from source in their own Docker container. This builds off of the CUDA 11.2.2 devel image on Dockerhub and contains the bare minimum packages to support cuSignal.
=> Add cusignal source dockerfile

docker/Dockerfile
Forward-merge triggered by push to `branch-0.19` that creates a PR to keep `branch-0.20` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> [gpuCI] Forward-merge branch-0.19 to branch-0.20 [skip ci]

ci/docs/build.sh
This PR removes the conda & pip installs from the doc build script since they're already included in our environment at build time.
=> Remove conda & pip installs from doc script

README.md, conda/environments/cusignal_base.yml, conda/environments/cusignal_full.yml
Closes https://github.com/rapidsai/cusignal/issues/356
README updates for cuSignal 0.19, expanded documentation on Docker builds, and bumped max CUDA version in conda environments to 11.2 from 10.2.
=> Update README and bump CUDA to max 11.2 from 10.2 in Conda environments

ci/benchmark/build.sh
Remove `defaults` channel from conda build
=> ENH Remove defaults channel from conda build

build.sh
The PR adds `--threads` compile feature when CTK version 11.2 or greater are detected during build.
The benefit is only seen will all CCs (e.g., sm_50, sm_60, sm_70, sm_80) are built. 
Performance example, on DGXA100
```bash
./build --allgpuarch
```
CTK 11.1
```bash
real    0m20.578s
user    0m55.533s
sys     0m5.241s
```
CTK 11.2
```bash
real    0m6.506s
user    1m10.992s
sys     0m12.081s
```
=> Speedup build for multi-arch compile

CHANGELOG.md
This PR updates the changelog for `branch-0.19`. I think the automated changelog script that we use was overlooked for a few repos during the `0.19` release.
=> Update `CHANGELOG.md` [skip ci]

CHANGELOG.md
This PR fixes the merge conflicts in #371.
This PR should be merged with a merge-commit (not with `@gpucibot merge`).
=> Merge `branch-0.19` into `branch-21.06` [skip ci]

conda/recipes/cusignal/meta.yaml
This PR updates the environment variable thats used to determine the `cuda_version` varaible in our conda recipes.
The `CUDA` environment variable is explicitly set by the Ops team in our Jenkins jobs, whereas `CUDA_VERSION` comes from the `nvidia/cuda` Docker images that we base our images from.
=> Update environment variable used to determine `cuda_version`

CHANGELOG.md, cpp/src/filtering/_upfirdn.cu, python/cusignal/filtering/_upfirdn_cuda.py, python/cusignal/filtering/filtering.py, python/cusignal/filtering/resample.py
This PR improves performance by adding `__builtin_assume`, leave `h` on CPU, and more efficient data movement
```bash
------------ benchmark 'UpFirDn': 36 tests ------------
Name (time in us)                        Mean          
-------------------------------------------------------
test_upfirdn_gpu[0-9-7-1-16384]      315.4922 (1.0)    
test_upfirdn_gpu[0-2-7-1-16384]      316.1258 (1.00)   
test_upfirdn_gpu[0-2-3-1-16384]      316.1944 (1.00)   
test_upfirdn_gpu[-1-9-7-1-16384]     316.5337 (1.00)   
test_upfirdn_gpu[0-1-3-1-16384]      317.2807 (1.01)   
test_upfirdn_gpu[-1-9-3-1-16384]     317.4403 (1.01)   
test_upfirdn_gpu[0-1-7-1-16384]      318.3329 (1.01)   
test_upfirdn_gpu[0-9-3-1-16384]      318.9417 (1.01)   
test_upfirdn_gpu[0-1-7-2-256]        318.9686 (1.01) …
```
=> Perf Improvements for UPFIRDN

cpp/src/filtering/_sosfilt.cu, python/cusignal/filtering/_sosfilt_cuda.py, python/cusignal/filtering/filtering.py
The PR speeds up SOS Filter by moving `zi` arithmetic to registers and remove required SMEM
```bash
--------------- benchmark 'SOSFilt': 12 tests ----------------
Name (time in ms)                               Mean          
--------------------------------------------------------------
test_sosfilt_gpu[float64-1-32768-32]          4.5768 (1.0)    
test_sosfilt_gpu[float64-10-32768-32]         4.5822 (1.00)   
test_sosfilt_gpu[float64-2-32768-32]          4.6098 (1.01)   
test_sosfilt_gpu[float64-1-32768-64]          4.8506 (1.06)   
test_sosfilt_gpu[float64-2-32768-64]          4.8632 (1.06)   
test_sosfilt_gpu[float64-10-32768-64]         4.8746 (1.07)   
test_sosfilt_gpu[float64-1-1048576-32]      156.1625 (34.12)  
test_sosfilt_gpu[float64-2-1048576-32]      156.2263 (34.13) …
```
=> Perf Improvements to SOS Filter

python/cusignal/__init__.py, python/cusignal/radartools/__init__.py, python/cusignal/radartools/radartools.py
Initial commit with seemingly correct logic for normalized ambiguity function for input signal `x`. Haven't worked cross correlation and only taking 1D cut through the AF.
Updates:
* Implemented `doppler` and `delay` techniques in addition to existing default `2d`.
* @mnicely optimized `2d`
* Need to look at areas for perf improvement w/ `doppler` and `delay`
* Need to write unit tests (pure python) and benchmarks
=> Add Ambiguity Function (ambgfun)

ci/gpu/build.sh
Fix errors when running CI/CD on cuSignal PRs with PyTorch and CTK 11.2 and 11.0.
cc @ajschmidt8 @jakirkham
=> Remove pytorch from cusignal CI/CD

ci/gpu/build.sh
Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> [gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip ci]

python/cusignal/radartools/beamformers.py
Previous version of mvdr beamformer failed to account for the fact that the `wA` denominator result is a scalar. Removing inverse and additional matmul in addition to adding elementwise kernel
=> mvdr perf optimizations and addition of elementwise divide kernel

python/cusignal/radartools/beamformers.py
Allow the option to pass in a covariance matrix, R, rather than computing it within the MVDR beamformer.
=> Bypass Covariance Matrix Calculation if Supplied in MVDR Beamformer

conda/recipes/cusignal/meta.yaml
Relaxes version constraints to allow CuPy 10.
xref: https://github.com/rapidsai/integration/pull/413
=> Allow CuPy 10

python/cusignal/test/test_waveforms.py, python/cusignal/waveforms/waveforms.py
This PR add parity with MATLAB chirp, specifically complex output.
Adding the following parameter (`dtype=cp.float64`)
Example input (`w = cusignal.chirp(t, cf-100, t[-1], cf+100, dtype=cp.complex128)`)
Perf on original
```bash
test/test_waveforms.py ........                                                                                                                                                                                                                                                               [100%]
-------------- benchmark 'Chirp': 8 tests --------------
Name (time in us)                         Mean          
--------------------------------------------------------
test_chirp_gpu[quad-10-1-6-16384]      61.1752 (1.0)    
test_chirp_gpu[lin-10-1-6-16384]       61.2585 …
```
=> adding complex parameter to chirp and additional tests

docs/source/conf.py
This PR fixes an issue with the doc builds. `get_html_theme_path()` was removed in the commit below. After some local testing, it seems that the lines in this PR can be removed without any issues.
- https://github.com/pydata/pydata-sphinx-theme/commit/579d7ce695cb5c2611aa7b8ab76fbc3efc5fab26
=> Fix docs builds

python/cusignal/convolution/__init__.py, python/cusignal/convolution/correlate.py
I implemented a `cusignal.correlation_lags`  which works as expected, with notable increase in speed as expected compared to the [Scipy function]( https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.correlation_lags.html).
I am still working on the pytest and will update that in [`test_convolution.py`](https://github.com/rapidsai/cusignal/blob/branch-22.04/python/cusignal/test/test_convolution.py) once completed soon.
=> [FEA] correlation lags function

python/cusignal/test/test_arraytools.py, python/cusignal/utils/arraytools.py
This PR makes some changes to `get_pinned_mem` so that it properly handles dtypes other than `uint8` - it also adds some additional handling for `shape` so that integers are now supported, and the output array actually has the input `shape`.
=> Extend `get_pinned_mem` to work with more dtype / shapes

python/cusignal/io/reader.py, python/cusignal/test/io/test_bin.py, python/cusignal/test/io/test_sigmf.py, python/cusignal/test/test_arraytools.py, python/cusignal/utils/arraytools.py
This PR resolve pinned buffer IO issues introduced in https://github.com/rapidsai/cusignal/commit/de9be48c5cd8b8dc15416cbaf540164c40a9bc94; essentially, if `read_bin` is passed a `buffer` and `dtype`, it should prioritize `buffer.dtype` over `dtype` to ensure that the buffer and memmap sizes match up.
Still want to add IO tests to ensure that things are working properly, and potentially alter `read_bin` to raise an error if both `buffer` and `dtype` are provided.
Closes #474
=> Fix pinned buffer IO issues

conda/recipes/cusignal/conda_build_config.yaml, conda/recipes/cusignal/meta.yaml
This PR enables the usage of conda compilers to build conda packages. This is required to use `mambabuild`
=> Use conda compilers

conda/recipes/cusignal/meta.yaml
Simplify recipes using `{{ target_platform }}` for `sysroot` package and `compiler()` function in `ignore_run_exports_from`
=> Simplify conda recipes

conda/recipes/cusignal/meta.yaml
Allows cuxfilter to be installed with CuPy 11.
xref: https://github.com/rapidsai/integration/pull/508
=> Allow CuPy 11

conda/recipes/cusignal/meta.yaml
Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> [gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

conda/recipes/cusignal/meta.yaml
The latest version of Numba (0.55) requires Numpy <= 1.22, but cuSignal currently pulls in Numpy 1.23+. Enforce upper bounds. @ajschmidt8 or other ops -- could we hot-fix this to the current 22.08 release too?
=> Fix Numpy / Numba mismatch

README.md
I recently spun up a new install of `cusignal` on my Windows 10 machine running WSL2. Once CUDA environment issues were sorted, everything went smoothly, except `pytest`. Current WSL install instructions need to include installation of `pytest-benchmark` to run `pytest`.
`conda create --name cusignal-dev`
`conda activate cusignal-dev`
`conda install numpy numba scipy cudatoolkit pip`
`pip install cupy-cuda118`
`./build.sh`
`pip install pytest`
`pytest`
<details>
<summary>Error output: </summary>
```bash
(cusignal-dev) evanmayer@Compy:~/github/cusignal-main/cusignal$ pytest
================================================ test session starts ================================================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: …
```
=> [REVIEW] Revisit WSL install instructions: additional dependency needed for pytest

README.md, ci/benchmark/build.sh
Aligns conda channel priority in the installation guide with changes made for the 22.10.01 hotfix.
=> Update channel priority

notebooks/api_guide/io_examples.ipynb
Adds the option to use a smaller ~300MB SigMF dataset for the IO examples, as well as code to automatically download / extract the dataset of choice.
Note that there are some failures in the notebook - raised #474 to cover this.
Closes https://github.com/rapidsai/cusignal/issues/472
=> Add option for smaller dataset in IO notebook

.github/workflows/build.yaml, .github/workflows/pr.yaml, .github/workflows/test.yaml, README.md, build.sh, ci/test_notebooks.sh, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/cusignal/meta.yaml, dependencies.yaml
This PR updates `cusignal` to build against branch [cuda-118](https://github.com/rapidsai/shared-action-workflows/compare/cuda-118) of the `shared-action-workflow` repository.
That branch contains updates for CUDA 11.8 and Python 3.10 packages.
I enabled `sm_90` support in builds using CUDA 11.8+.
It also includes some minor file renames.
=> Build CUDA 11.8 and Python 3.10 Packages

README.md
Closes https://github.com/rapidsai/cusignal/issues/535 by instructing users to specifying the CUDA Toolkit is added to the `PATH` and `LD_LIBRARY_PATH` environment variables from a fresh install of JetPack.
=> Add path instructions for Jetson users with fresh JP installs

conda/recipes/cusignal/meta.yaml
This PR moves the date string from the version to the build string for conda recipes in this repository.
This is necessary to ensure that the conda packages resulting from PR builds can be installed in the same environment as nightly conda packages, which is useful for testing purposes.
Additionally, this prevents a bug from occurring where the Python builds fail because the date string it computes is different than the one computed by the C++ build, therefore causing the Python build to search for a C++ build artifact that doesn't exist.
xref: https://github.com/rapidsai/rmm/pull/1195
=> Move date to build string in `conda` recipe

.github/workflows/build.yaml, .github/workflows/pr.yaml, .github/workflows/test.yaml, README.md, conda/environments/all_cuda-118_arch-x86_64.yaml, dependencies.yaml
This PR drops Python 3.8 in favor of 3.9.
=> Dropping Python 3.8

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/recipes/cusignal/meta.yaml, dependencies.yaml, python/cusignal/convolution/_convolution_cuda.py
* Require Numba 0.57+ consistently
* Require NumPy 1.21+ (to align with [Numba 0.57.0's NumPy minimum]( https://github.com/numba/numba/blob/0.57.0/setup.py#L25 ))
* Allow NumPy 1.24 (soften upper bounds)
* Replace deprecated `np.int` with `int`
=> Refresh requirements

.github/workflows/build.yaml, .github/workflows/pr.yaml, .github/workflows/test.yaml
This PR ensures that changes to the `shared-action-workflows` repository to support CUDA 12 won't affect cusignal. We are not planning to add CUDA 12 packaging for cusignal, as the repository is now deprecated (https://docs.rapids.ai/notices/rsn0032/).
This PR must be merged before https://github.com/rapidsai/shared-action-workflows/pull/101.
=> Only run cusignal CI for CUDA 11.
